plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/dalli-elasticache.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
